### ISSUE TITLE
Change /resources to /handouts

### ISSUE THREAD

**Issue by yoninachmany** [AsylumConnect/asylumconnect.github.io#32]
<img width="1280" alt="screen shot 2016-10-05 at 4 09 58 pm" src="https://cloud.githubusercontent.com/assets/4250521/19129841/cb98932e-8b16-11e6-81d3-33a3dab9e308.png">
<img width="1094" alt="screen shot 2016-10-05 at 4 09 36 pm" src="https://cloud.githubusercontent.com/assets/4250521/19129840/cb927e44-8b16-11e6-9704-1ad0202ac04b.png">
<img width="1277" alt="screen shot 2016-10-05 at 4 15 06 pm" src="https://cloud.githubusercontent.com/assets/4250521/19129871/ecdc1bf0-8b16-11e6-8249-a071a00f7b6e.png">
<img width="1280" alt="screen shot 2016-10-05 at 4 14 53 pm" src="https://cloud.githubusercontent.com/assets/4250521/19129872/ecdf12c4-8b16-11e6-93c8-202784050ec0.png">

**Comment by sen-lu** [comment]
related to #31
